Removed the stack things for now. Upgraded ghostscript, homebrew, imagemagick to the new way.

diff --git a/ghostscript b/ghostscript
--- a/ghostscript
+++ b/ghostscript
@@ -3,8 +3,14 @@
 #@file
 #Installs/Uninstalls GhostScript
 
-# Libs
-source ${HOME}/.bash_functions/msgs
+this_dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
+if [ -f ${this_dir}/bootstrap.sh ]; then
+  source ${this_dir}/bootstrap.sh
+else
+  echo -e "\nCouldn't find bootstrap.sh! Ooooh noooo\n"
+  exit 1
+fi
+
 
 # Checks
 if [ -z $(which brew) ]; then
@@ -12,18 +18,25 @@ if [ -z $(which brew) ]; then
   exit 1
 fi
 
-# Uninstall
-if [ "${1}" == "destroy" ] || [ "${1}" == "rebuild" ]; then
-  good_msg "Uninstalling GhostScript"
-  brew rmtree ghostscript
 
-  # If destroying, stop here.
-  if [ "${1}" == "destroy" ]; then
-    exit 0
-  fi
-fi
+#Goooo
+case "${1}" in
 
-# Install
-good_msg "Installing GhostScript"
-brew install ghostscript
+  'install')
+    neutral_msg "Installing GhostScript"
+    brew install ghostscript
+    ;;
+
+  'uninstall')
+    neutral_msg "Uninstalling GhostScript"
+    brew rmtree ghostscript
+    ;;
+
+  'rebuild')
+    $0 uninstall
+    sleep 1
+    $0 install
+    ;;
+
+esac
 
diff --git a/homebrew b/homebrew
--- a/homebrew
+++ b/homebrew
@@ -3,26 +3,37 @@
 #@file
 #Installs/Uninstalls Homebrew
 
-# Libs
-source ${HOME}/.bash_functions/msgs
 
-# Uninstall
-if [ "${1}" == "destroy" ] || [ "${1}" == "rebuild" ]; then
-  good_msg "Uninstalling Homebrew"
-
-  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
-
-  # If destroying, stop here.
-  if [ "${1}" == "destroy" ]; then
-    exit 0
-  fi
+this_dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
+if [ -f ${this_dir}/bootstrap.sh ]; then
+  source ${this_dir}/bootstrap.sh
+else
+  echo -e "\nCouldn't find bootstrap.sh! Ooooh noooo\n"
+  exit 1
 fi
 
-# Install
-good_msg "Installing Homebrew"
 
-ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+#Goooo
+case "${1}" in
 
-# Rmtree is used in a lot of other scripts here to remove dependencies
-brew tap beeftornado/rmtree && brew install beeftornado/rmtree/brew-rmtree
+  'install')
+    neutral_msg "Installing Homebrew"
+    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+
+    # Rmtree is used in a lot of other scripts here to remove dependencies
+    brew tap beeftornado/rmtree && brew install beeftornado/rmtree/brew-rmtree
+    ;;
+
+  'uninstall')
+    neutral_msg "Uninstalling Homebrew"
+    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
+    ;;
+
+  'rebuild')
+    $0 uninstall
+    sleep 1
+    $0 install
+    ;;
+
+esac
 
diff --git a/imagemagick b/imagemagick
--- a/imagemagick
+++ b/imagemagick
@@ -3,24 +3,40 @@
 #@file
 #Installs/Uninstalls ImageMagick
 
+this_dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
+if [ -f ${this_dir}/bootstrap.sh ]; then
+  source ${this_dir}/bootstrap.sh
+else
+  echo -e "\nCouldn't find bootstrap.sh! Ooooh noooo\n"
+  exit 1
+fi
+
+
 # Checks
 if [ -z $(which brew) ]; then
   echo -e "\nYou need to install Homebrew first.\n"
   exit 1
 fi
 
-# Uninstall
-if [ "${1}" == "destroy" ] || [ "${1}" == "rebuild" ]; then
-  echo -e "\nUninstalling ImageMagick.\n"
-  brew rmtree imagemagick
 
-  # If destroying, stop here.
-  if [ "${1}" == "destroy" ]; then
-    exit 0
-  fi
-fi
+#Goooo
+case "${1}" in
 
-# Install
-echo -e "\nInstalling ImageMagick.\n"
-brew install imagemagick --with-libtiff
+  'install')
+    neutral_msg "Installing ImageMagick."
+    brew install imagemagick --with-libtiff
+    ;;
+
+  'uninstall')
+    neutral_msg "Uninstalling ImageMagick."
+    brew rmtree imagemagick
+    ;;
+
+  'rebuild')
+    $0 uninstall
+    sleep 1
+    $0 install
+    ;;
+
+esac
 
